openapi: 3.0.0
info:
  title: Admin API
  description: API for administrative tasks
  version: 1.0.0

servers:
  - url: "https://admin.dev-site.io"

paths:
  /admin/users:
    get:
      operationId: getAllUsers
      summary: Get all users
      description: Retrieve a list of all users
      tags:
        - Operations
      security:
        - apiKeyAuth: []
   
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    username:
                      type: string
                      example: 'dan.e'
                    email:
                      type: string
                      example: 'dan.english@redocly.com'

  /admin/users/{userId}:
    get:
      operationId: getUser
      summary: Get user by ID
      description: Retrieve user details by ID
      tags:
        - Operations
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
          description: ID of the user to retrieve
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  username:
                    type: string
                    example: 'dan.e'
                  email:
                    type: string
                    example: 'dan.english@redocly.com'
      security:
        - apiKeyAuth: []
    delete:
      operationId: deleteUser
      summary: Delete user by ID
      description: Delete a user by ID
      tags:
        - Operations
      security:
        - apiKeyAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
          description: ID of the user to delete
      responses:
        '204':
          description: User deleted successfully

  /admin/users/{userId}/reset-password:
    post:
      operationId: resetUserPassword
      summary: Reset user password
      description: Reset the password for a user
      tags:
        - Operations
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
          description: ID of the user to reset password for
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                newPassword:
                  type: string
                  description: New password for the user
                  example: 'p@ssw0rd'
      responses:
        '200':
          description: Password reset successful
      security:
        - apiKeyAuth: []
components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: API key required to access the Admin API
tags:
  - name: Operations
    description: Operational information.