openapi: 3.0.0
info:
  title: Admin API
  description: API for administrative tasks
  version: 1.0.0

paths:
  /admin/users:
    get:
      summary: Get all users
      description: Retrieve a list of all users
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    username:
                      type: string
                    email:
                      type: string

  /admin/users/{userId}:
    get:
      summary: Get user by ID
      description: Retrieve user details by ID
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
          description: ID of the user to retrieve
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  username:
                    type: string
                  email:
                    type: string

    delete:
      summary: Delete user by ID
      description: Delete a user by ID
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
          description: ID of the user to delete
      responses:
        '204':
          description: User deleted successfully

  /admin/users/{userId}/reset-password:
    post:
      summary: Reset user password
      description: Reset the password for a user
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
          description: ID of the user to reset password for
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                newPassword:
                  type: string
                  description: New password for the user
      responses:
        '200':
          description: Password reset successful

components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: API key required to access the Admin API
