name: Dynamic Sidebar Generation

on:
  push:
    branches:
      - '**'

jobs:


  test:
    name: Dynamic Nav
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: dynamic_navigation
        run: python todo_List.py

      - name: stage changed files
        run: git add .

      - name: add gituser
        run: git config --global user.email "you@example.com"; git config --global user.name "Your Name"

      - name: commit changed files
        run: git commit -m "Auto creating sidebar"


