name: Dynamic Sidebar Generation

on:
  push:
    branches:
      - '**'

jobs:


  test:
    name: Dynamic Nav
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - uses: actions/checkout@v4
      - name: dynamic_navigation
        run: python todo_List.py
