name: Dynamic Sidebar Generation

on:
  push:
    branches:
      - '**'

jobs:
  reunite-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - name: dynamic_navigation
        run: python .github/workflows/todo_List.py
